version: "3.8"

services:
  postgresdb:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - app-net
    environment:
      - POSTGRES_PASSWORD=Dancik!)@())
  todolistapp:
    build: .
    ports:
      - "80:80"
    networks:
      - app-net
    environment:
      - ConnectionString__PostGresSql=User ID=postgres;Password=Dancik!)@());Host=postgresdb;Port=5432;Database=ToDoListAppDB
    depends_on:
      - postgresdb
    entrypoint: ["./wait-for-it.sh", "db:5432", "--", "dotnet", "ToDoList.dll"]
networks:
  app-net:
    driver: bridge